name: speech_recognition
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

flutter:
  plugin:
    androidPackage: bz.rxla.flutter.speechrecognition
    pluginClass: SpeechRecognitionPlugin

dependencies:
  flutter:
    sdk: flutter
